[package]
name = "ztracing-gpui-unofficial"
version = "1.19.0-pre"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/iamnbutler/gpui-unofficial"
description = "Unofficial release of Zed's ztracing crate"

[features]
tracy = ["tracing-tracy", "tracy-client"]
web = ["dep:async-channel", "dep:js-sys", "dep:wasm-bindgen", "dep:web-sys"]

[dependencies]
zlog = { package = "zlog-gpui-unofficial", version = "1.19.0-pre" }
tracing = { version = "0.1.40" }

tracing-subscriber = "0.3.22"
ztracing_macro = { package = "ztracing-macro-gpui-unofficial", version = "1.19.0-pre" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tracing-tracy = { version = "0.11.4", optional = true, features = ["enable", "ondemand"] }
tracy-client = { version = "0.18.2", optional = true, features = ["enable", "ondemand"] }

[target.'cfg(target_family = "wasm")'.dependencies]
async-channel = { version = "2.5.0", optional = true }
js-sys = { version = "0.3", optional = true }
wasm-bindgen = { version = "0.2.120", optional = true }
web-sys = { version = "0.3", features = ["console", "Performance"], optional = true }

[lints]
rust = { unexpected_cfgs = { level = "warn", check-cfg = ["cfg(ztracing)", "cfg(ztracing_with_memory)"] } }

[workspace]
